import = [
  "~/.config/alacritty/themes/wombat.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12
normal.family = "MesloLGS NF"

[window]
blur = true
opacity = 0.7
padding = { x = 10, y = 10 }
decorations = "Buttonless"
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Enter", mods = "Command", action = "ToggleMaximized" },
  { key = "C", mods = "Alt|Shift", action = "ToggleViMode" },
]

# [shell]
# program = "/opt/homebrew/bin/zellij"
